export interface Variable {
  name: string;
  db_name: string;
  //TODO Add more about the variable?
}

export const DisplayNames = {
  tphys: "Evolution Time",
  kstar_1: "Evolutionary State(P)",
  mass0_1: "Previous Stage Mass(P)",
  mass_1: "Mass(P)",
  lumin_1: "Luminosity(P)",
  rad_1: "Radius(P)",
  teff_1: "Effective Temperature(P)",
  massc_1: "Core Mass(P)",
  radc_1: "Core Radius(P)",
  menv_1: "Envelope Mass(P)",
  renv_1: "Envelope Radius(P)",
  epoch_1: "Epoch(P)",
  ospin_1: "Spin(P)",
  deltam_1: "Mass Transfer Rate(P)",
  rrol_1: "Radius in units of Roche lobe radii(P)",
  b_0_1: "Neutron Star Magnetic Field(P)",
  sn_1: "Supernova Type(P)",
  kstar_2: "Evolutionary State(S)",
  mass0_2: "Previous Stage Mass(S)",
  mass_2: "Mass(S)",
  lumin_2: "Luminosity(S)",
  rad_2: "Radius(S)",
  teff_2: "Effective Temperature(S)",
  massc_2: "Core Mass(S)",
  radc_2: "Core Radius(S)",
  menv_2: "Envelope Mass(S)",
  renv_2: "Envelope Radius(S)",
  epoch_2: "Epoch(S)",
  ospin_2: "Spin(S)",
  deltam_2: "Mass Transfer Rate(S)",
  rrol_2: "Radius in units of Roche lobe radii(S)",
  b_0_2: "Neutron Star Magnetic Field(S)",
  sn_2: "Supernova Type(S)",
  porb: "Orbital Period",
  sep: "Semimajor Axis",
  ecc: "Eccentricity",
  bin_state: "State of the Binary",
  merger_type: "String of the kstar's in the merger, '-001' if not merged",
  bin_num: "Unique binary Index",
}
