# Generated by Django 3.1.6 on 2021-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryStar',
            fields=[
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('tphys', models.FloatField(blank=True, null=True)),
                ('kstar_1', models.FloatField(blank=True, null=True)),
                ('mass0_1', models.FloatField(blank=True, null=True)),
                ('mass_1', models.FloatField(blank=True, null=True)),
                ('lumin_1', models.FloatField(blank=True, null=True)),
                ('rad_1', models.FloatField(blank=True, null=True)),
                ('teff_1', models.FloatField(blank=True, null=True)),
                ('massc_1', models.FloatField(blank=True, null=True)),
                ('radc_1', models.FloatField(blank=True, null=True)),
                ('menv_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('renv_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('epoch_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ospin_1', models.FloatField(blank=True, null=True)),
                ('deltam_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rrol_1', models.FloatField(blank=True, null=True)),
                ('kstar_2', models.FloatField(blank=True, null=True)),
                ('mass0_2', models.FloatField(blank=True, null=True)),
                ('mass_2', models.FloatField(blank=True, null=True)),
                ('lumin_2', models.FloatField(blank=True, null=True)),
                ('rad_2', models.FloatField(blank=True, null=True)),
                ('teff_2', models.FloatField(blank=True, null=True)),
                ('massc_2', models.FloatField(blank=True, null=True)),
                ('radc_2', models.FloatField(blank=True, null=True)),
                ('menv_2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('renv_2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('epoch_2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ospin_2', models.FloatField(blank=True, null=True)),
                ('deltam_2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rrol_2', models.FloatField(blank=True, null=True)),
                ('porb', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('ecc', models.FloatField(blank=True, null=True)),
                ('b_0_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('b_0_2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('snkick_1', models.FloatField(blank=True, null=True)),
                ('snkick_2', models.FloatField(blank=True, null=True)),
                ('vsys_final', models.FloatField(blank=True, null=True)),
                ('sntheta_final', models.FloatField(blank=True, null=True)),
                ('sn_1', models.FloatField(blank=True, null=True)),
                ('sn_2', models.FloatField(blank=True, null=True)),
                ('bin_state', models.SmallIntegerField(blank=True, null=True)),
                ('merger_type', models.SmallIntegerField(blank=True, null=True)),
                ('bin_num', models.SmallIntegerField(blank=True, null=True)),
                ('time_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'binary_stars',
                'managed': False,
            },
        ),
    ]
