# Generated by Django 3.1.7 on 2021-04-23 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('binarystars', '0002_attribute_interpolatedbinarystars'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.JSONField(editable=False)),
                ('finished', models.BooleanField(default=False)),
                ('response', models.JSONField()),
            ],
            options={
                'db_table': 'queue',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'managed': True},
        ),
    ]
