# Generated by Django 3.1.7 on 2021-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binarystars', '0004_clusterqueue_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterqueue',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
